name: Flying Macaw Films
favicon: null
layout_spectrum: 0.39609487308189273
typography_spectrum: 0.6730319452472031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6489205374382436
  lightness: 0.041881626937538385
  saturation: 0.09674372943118215
  rhythmicContrast: 0.24675355479121208
purpose: []
